# Site settings
#title: My Personal Blog
#description: Hi I am Taapas Agrawal.
keywords: Modern, Blogging, Fun
author: Taapas
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

title: My personal blog - Taapas Agrawal
email: taapas2897@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi this is Taapas Agrawal and this is my personal blogging website. :)
permalink: ':title/'
baseurl: "/taapas-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Contact links
email: taapas2897@gmail.com
phone: 7355281756
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: taapas1128 # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

